routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/', 'SiteController@index')->name('home');

Route::get('/categories/{slug}', 'CategoriesController@show')->name('categories');

Route::get('/products/{slug}', 'ProductsController@show')->name('products');

Route::get('/about', 'PagesController@about')->name('about');
Route::get('/contacts', 'PagesController@contacts')->name('contacts');

Route::get('design-interior', 'DesignInteriorsController@index')->name('design-interior');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function(){
    Route::get('/', 'CategoriesController@index')->name('admin');

    Route::resource('/categories', 'CategoriesController');
    Route::get('/category-by-style/{id}', 'CategoriesController@getCategoriesByStyle')->name('category-by-style');

    Route::resource('/styles', 'StylesController');

    Route::resource('/pages', 'PagesController');

    Route::resource('/products', 'ProductsController');

    Route::resource('/designinteriors', 'DesignInteriorController');

    Route::get('/siteinfo', 'SiteinfosController@index')->name('siteinfo.index');
    Route::get('/siteinfo/edit', 'SiteinfosController@edit')->name('siteinfo.edit');
    Route::put('/siteinfo/{siteinfo}', 'SiteinfosController@update')->name('siteinfo.update');

    Route::resource('/administrators', 'AdministratorsController');
    Route::resource('/slideshows', 'BannerSlideshowController');
});

resources/views/admin/slideshows/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: kalbekovnurpeyis
 * Date: 1/6/19
 * Time: 18:10
 */

resources/views/admin/slideshows/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: kalbekovnurpeyis
 * Date: 1/6/19
 * Time: 18:11
 */

resources/views/admin/slideshows/index.blade.php
@extends('admin.layouts.layout')

@section('content')
    <div class="card mt-5">
        <div class="card-body">
            <div class="row align-items-center">
                <div class="col-md-9">
                    <h4 class="header-title">Список записей</h4>
                </div>
                <div class="col-md-3">
                    <a href="{{ route('slideshows.create') }}">
                        <button type="button" class="btn btn-primary btn-xs btn-block form-group">
                            Создать новую
                        </button>
                    </a>
                </div>
            </div>

            <div class="single-table">
                <div class="table-responsive">
                    @if($slideshows->total())
                        <table class="table table-hover progress-table text-center">
                            <thead class="text-uppercase">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Изображение</th>
                                <th scope="col">Название</th>
                                <th scope="col">Действие</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($slideshows as $slideshow)
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <th scope="row">
                                        <img src="/uploads/200x200-{{ $slideshow->image }}" width="50px" height="50px" alt="">
                                    </th>
                                    <td>{{ $slideshow->title }}</td>
                                    <td>
                                        <ul class="d-flex justify-content-center">
                                            <li class="mr-3">
                                                <a href="{{ route('slideshows.edit', $slideshow->id) }}" class="text-secondary">
                                                    <i class="ti-pencil-alt"></i>
                                                </a>
                                            </li>
                                            <li>
                                                {!! Form::open(['route' => ['slideshows.destroy', $slideshow->id], 'method' => 'delete']) !!}
                                                <button type="submit" class="text-danger wrap-btn" onclick="return confirm('Вы уверены?')">
                                                    <i class="ti-trash"></i>
                                                </button>
                                                {!! Form::close() !!}
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <nav class="d-flex justify-content-end mt-3 pt-3 border-top">
                            {{ $slideshows->links() }}
                        </nav>
                    @else
                        <p class="text-muted font-14 mb-4">Нет записей</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection